### ISSUE TITLE
Migrate oc connection plugin to this collection

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.okd#19]
This connection plugin currently exists in the community.general collection. With active development moving to this collection this plugin should be migrated once a release of community.okd is made according to [the documented procedures](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#migrating-ansible-content-to-a-different-collection).

- [x] Add the plugin to community.okd

Once a release of community.okd is available:

- [x] Create a PR against community.general to remove the plugin and [additional steps here](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#removing-the-content-from-the-old-collection)
- [ ] Update the ansible/ansible:devel branch entries for all files moved

**Comment by geerlingguy** [comment]
For:

> Update the ansible/ansible:devel branch entries for all files moved

That might not be necessary—since this collection didn't make it to 2.10, we will need to add the routing in `community.general` so references will go through there... I think.

We might be the first plugin to be attempting this, so it might be best to ask @gundalow or someone else working on community side to figure out the best approach for moving the `oc` plugin from community.general to community.okd.

**Comment by geerlingguy** [comment]
I _believe_ we will be good to go after https://github.com/ansible-collections/community.general/pull/866 is merged.

It seems like there have been a couple other modules that have been moved prior to 2.11, like `conjur_variable`, which I used as a template for this move.

**Comment by tima** [comment]
See https://github.com/ansible-collections/community.general/pull/866#issuecomment-687451553 for last step.
