### ISSUE TITLE
Add special idempotent handling to `k8s` module for OpenShift DeploymentConfig resources

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.okd#30]
##### SUMMARY

Create a module for creating and effectively managing OpenShift DeploymentConfigs in an straightforward  idempotent way.  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

plugins/modules/k8s.py

##### ADDITIONAL INFORMATION

While a DeploymentConfig could be created and managed through the `k8s` module, you have to manage the relationships to associated resources like ImageStreams in your play. This module encodes and encapsulates that logic for managing these relationships and does so in a safe and idempotent way.

This feature request is based on feedback from the field regarding the management of DeploymentConfigs in Operators using Ansible where, incorrectly handled, one can create a recursive reconciliation loop.

**UPDATE:** This feature request has been updated to add logic to the `k8s` module rather than the a dedicated module based on [feedback in the comments here](https://github.com/ansible-collections/community.okd/issues/30#issuecomment-689262810).

**Comment by sabre1041** [comment]
While ImageStreams are traditionally placed on `DeploymentConfigs`, they can also be added as annotations to native Kubernetes objects, so logic should be added to manage whether this annotation is present

https://developers.redhat.com/blog/2019/09/20/using-red-hat-openshift-image-streams-with-kubernetes-deployments/

**Comment by fabianvf** [comment]
I think rather than a separate module it would make sense to determine whether the image field is being set by an image stream and remove that bit of the patch from the payload if it is. This allows people to interact with deployment configs normally through the k8s module, which means that if they are doing things like loading all resource definitions from a directory or URL, or dealing with multi-document yaml, they don't need to filter out deployment configs and handle them specially. This also lets us put in the extra handling of the annotations (thanks for that note) without the user needing to think about it at all

**Comment by tima** [comment]
I've updated the title of this issue and the description to reflect [@fabianvf's recommendation here](https://github.com/ansible-collections/community.okd/issues/30#issuecomment-689665193).
